name: Continuous Delivery

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker
          docker build -t us-east4-docker.pkg.dev/prueba-174817/latam-test:latest .
          docker push us-east4-docker.pkg.dev/prueba-174817/latam-test:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud config set project latam-test
          gcloud auth activate-service-account --key-file=<(echo $GCP_KEY)
          gcloud run deploy latam-test --image us-east4-docker.pkg.dev/prueba-174817/latam-test --platform managed --region us-east4

      - name: Set up GCP credentials
        run: echo "$GCP_KEY" > "$HOME"/gcp-key.json
